version: '2'

services:

    web:
        container_name: ${SITE_NAME}_web
        image: wexample/wexphp7:latest
        stdin_open: true
        tty: true
        ports:
          - "${HOST_PORT_HTTPD}:80"
        volumes:
          - .:/var/www/html
          - ./env/apache/site.${SITE_ENV}.conf:/etc/apache2/sites-available/000-default.conf
          - ${DATA_DUMPS_PATH}:/var/www/dumps
        links:
          - mysql

    mysql:
        container_name: ${SITE_NAME}_mysql
        image: wexample/wexmysql:latest
        ports:
            - '${HOST_MYSQL_PORT}:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=${HOST_MYSQL_PASSWORD}
            - MYSQL_DATABASE=${SITE_NAME}
            - MYSQL_USER=${HOST_MYSQL_USER}
            - MYSQL_PASSWORD=${HOST_MYSQL_PASSWORD}
        volumes:
            - ${DATA_STORAGE_PATH}:/var/lib/mysql

    phpmyadmin:
        container_name: ${SITE_NAME}_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
          - PMA_HOST=${SITE_NAME}_mysql
        restart: always
        ports:
          - '${HOST_PHPMYADMIN_PORT}:80'
        links:
          - mysql:mysql
